import { createFileRoute } from "@tanstack/react-router";
import { ArrowRight, BarChart3, CheckCircle2, Gauge, Layers3, MessageSquareMore, MousePointerClick } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { AnalyticsPreview, AutomationFlow, FormVsFunnelSlider, IndustryScene, JourneyDiagram, LeadScorePlayground, PhoneFrameDemo, SampleExperienceCards } from "@/components/interactive/InteractiveShowcase";
import { FunnelDemo } from "@/features/funnel-demo/FunnelDemo";
import { configs } from "@/features/funnel-demo/configs";
import { faqs, industries, serviceGroups } from "@/content/site";

const description="We build and manage gamified funnels, quizzes, assessments and calculators that capture, qualify and score leads, then automate WhatsApp and CRM follow-up.";
export const Route = createFileRoute("/")({head:()=>({meta:[{title:"TezPlay | Interactive Lead Generation & Qualification Agency"},{name:"description",content:description},{property:"og:title",content:"TezPlay | Interactive Lead Generation & Qualification Agency"},{property:"og:description",content:description},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary_large_image"}],links:[{rel:"canonical",href:"/"}],scripts:[{type:"application/ld+json",children:JSON.stringify({"@context":"https://schema.org","@graph":[{"@type":"Organization",name:"TezPlay",url:"/"},{"@type":"WebSite",name:"TezPlay",url:"/"},{"@type":"FAQPage",mainEntity:faqs.map(([name,text])=>({"@type":"Question",name,acceptedAnswer:{"@type":"Answer",text}}))}]})}]}),component:Home});

function Home(){return <>
  <section className="hero"><div className="container hero-grid"><div className="hero-copy"><span className="eyebrow">Interactive lead generation agency</span><h1>Turn Clicks Into Play. Turn Play Into <em>Qualified Leads.</em></h1><p>We build and manage quizzes, assessments, calculators and gamified campaigns that capture intent, qualify leads and trigger automated follow-up.</p><div className="button-row"><Button asChild size="lg"><a href="/request-proposal">Request a Proposal <ArrowRight/></a></Button><Button asChild variant="outline" size="lg"><a href="/sample-experiences">Try a Sample Experience</a></Button></div><div className="micro-line"><span><CheckCircle2/>Custom-built</span><span><CheckCircle2/>Lead qualification</span><span><CheckCircle2/>CRM & WhatsApp follow-up</span></div></div><PhoneFrameDemo/></div></section>
  <div className="industry-strip"><div className="container"><span>Built for teams in</span>{["Healthcare","Real Estate","SaaS & ERP","Education","Automotive","E-commerce","Agencies"].map(x=><strong key={x}>{x}</strong>)}</div></div>
  <Section eyebrow="Why interactive" title="Static Forms Capture Details. TezPlay Captures Intent." sub="A form tells you who submitted. An interactive experience tells you what they need and how ready they are."><FormVsFunnelSlider/></Section>
  <Section soft eyebrow="The connected journey" title="From Ad Click to Qualified Lead" sub="One connected journey, built and managed by us."><JourneyDiagram/><TextLink href="/how-we-work">See how we work</TextLink></Section>
  <Section eyebrow="Our services" title="What We Build and Manage"><div className="service-grid">{serviceGroups.map((x,i)=><article className="service-card" key={x.title}><span className="service-icon">{[<MousePointerClick/>,<Gauge/>,<BarChart3/>,<MessageSquareMore/>,<Layers3/>][i]}</span><span className="card-number">0{i+1}</span><h3>{x.title}</h3><p>{x.promise}</p><ul>{x.links.map(([name])=><li key={name}>{name}</li>)}</ul><a href={x.links[0][1]}>Explore this service <ArrowRight/></a></article>)}</div><Button asChild variant="outline"><a href="/services">View all 14 services</a></Button></Section>
  <Section dark eyebrow="Live samples" title="Try Them Yourself" sub="Live samples of the experiences we build. Everything here is demo content."><SampleExperienceCards/><Button asChild><a href="/sample-experiences">Browse all sample experiences</a></Button></Section>
  <Section eyebrow="Lead intelligence" title="Not Every Lead Is Equal" sub="We turn answers into a clear score and next action your sales team can act on. Scoring rules are agreed with you, so they reflect how you actually sell."><LeadScorePlayground/><p className="caption">Sample scoring logic for illustration.</p></Section>
  <Section soft eyebrow="Follow-up" title="Qualification Should Trigger Action" sub="Route each lead to the right follow-up automatically: WhatsApp, email, CRM and sales alerts."><AutomationFlow/><p className="caption">We can connect leads to systems such as HubSpot, Zoho, Salesforce, Twenty CRM, email tools and WhatsApp Business, depending on your setup.</p></Section>
  <Section eyebrow="Industry solutions" title="Interactive Lead Generation for Your Industry"><div className="industry-grid">{industries.map(x=><article className="industry-card" key={x.slug}><IndustryScene kind={x.name}/><h3>{x.name}</h3><ul>{x.items.map(y=><li key={y}>{y}</li>)}</ul><a href={`/industries/${x.slug}`}>View industry solution <ArrowRight/></a></article>)}</div></Section>
  <Section soft eyebrow="Sample funnels" title="See Qualification in Action"><Tabs defaultValue="health"><TabsList className="demo-tabs"><TabsTrigger value="health">Healthcare</TabsTrigger><TabsTrigger value="realty">Real Estate</TabsTrigger><TabsTrigger value="saas">SaaS & ERP</TabsTrigger></TabsList><TabsContent value="health"><DemoBlock title="Sample: Find the Right Care Path" config="healthcare-care-path"/></TabsContent><TabsContent value="realty"><DemoBlock title="Sample: Find Your Ideal Property" config="real-estate-finder"/></TabsContent><TabsContent value="saas"><DemoBlock title="Sample: Find the Right Business Software" config="saas-erp-finder"/></TabsContent></Tabs></Section>
  <Section eyebrow="Our process" title="A Clear Process, From Idea to Optimized Campaign"><div className="process-grid">{[["Discover","Goals, audience, sales process and what makes a lead qualified."],["Design","Experience concept, questions, scoring rules and result screens."],["Build & Connect","Development, landing page and follow-up setup."],["Launch","Go-live, tracking checks and ad connection if in scope."],["Optimize","Analyse drop-offs, lead quality and iterate."]].map((x,i)=><article key={x[0]}><span>{i+1}</span><h3>{x[0]}</h3><p>{x[1]}</p></article>)}</div><TextLink href="/how-we-work">See the full process</TextLink></Section>
  <Section dark eyebrow="Campaign clarity" title="See More Than Form Submissions" sub="Track starts, completions, qualified leads and cost per lead, and see where people drop off."><AnalyticsPreview/></Section>
  <Section eyebrow="Proof, without the theatre" title="Case Studies"><div className="empty-proof"><h3>Detailed stories are in preparation.</h3><p>We’re preparing detailed case studies. Want to be among the first campaigns we feature?</p><Button asChild><a href="/request-proposal">Request a Proposal</a></Button></div></Section>
  <Section soft eyebrow="Resources" title="Learn How Interactive Lead Generation Works"><div className="resource-grid">{["What is gamified lead generation?","Quiz funnels vs landing pages","How to qualify leads automatically"].map((x,i)=><a href="/resources" key={x}><span>GUIDE 0{i+1}</span><h3>{x}</h3><p>Practical ideas for turning campaign interactions into useful sales context.</p><ArrowRight/></a>)}</div></Section>
  <Section eyebrow="Frequently asked questions" title="Straight Answers Before We Start"><Accordion type="single" collapsible className="faq">{faqs.map(([q,a],i)=><AccordionItem value={`${i}`} key={q}><AccordionTrigger>{q}</AccordionTrigger><AccordionContent><p>{a}</p></AccordionContent></AccordionItem>)}</Accordion></Section>
  <section className="final-cta"><div className="container"><span className="eyebrow">Ready when you are</span><h2>Your Next Lead Should Tell You More Than Their Phone Number.</h2><p>Tell us about your goals and we’ll propose an interactive campaign that captures intent, qualifies leads and follows up automatically.</p><div className="button-row"><Button asChild size="lg"><a href="/request-proposal">Request a Proposal</a></Button><Button asChild variant="outline" size="lg"><a href="/contact#strategy-call">Book a Strategy Call</a></Button></div></div></section>
  </>}
function Section({eyebrow,title,sub,children,soft=false,dark=false}:{eyebrow:string;title:string;sub?:string;children:React.ReactNode;soft?:boolean;dark?:boolean}){const id=title.toLowerCase().replace(/[^a-z]+/g,"-");return <section className={`section ${soft?"soft":""} ${dark?"dark-section":""}`} aria-labelledby={id}><div className="container"><header className="section-heading"><span className="eyebrow">{eyebrow}</span><h2 id={id}>{title}</h2>{sub&&<p>{sub}</p>}</header>{children}</div></section>}
function TextLink({href,children}:{href:string;children:React.ReactNode}){return <a className="text-link" href={href}>{children}<ArrowRight/></a>}
function DemoBlock({title,config}:{title:string;config:keyof typeof configs}){return <div className="embedded-demo"><div><span className="sample-badge">Interactive sample</span><h3>{title}</h3><p>Answer a few sample questions to see how qualification creates a clearer next action.</p></div><FunnelDemo config={configs[config]}/></div>}